@startuml

title Distributing Content via Inspiria Webhook

box "EdTech Books" #LightBlue
    participant "Author" as author
    participant "EdTech Books" as edTechBooks
end box

box "Inspiria" #LightGreen
    participant "Webhook" as webhook
    participant "Content Updater" as contentUpdater
    participant "MPN Server" as mpnServer
    participant "Mobile App" as mobileApp
    participant "API" as api
    participant "Database" as database
end box

==Notify webhook of updated book==
author -> edTechBooks++: Update Book
note right: Enqueue
edTechBooks -> webhook++: Book Updated
note left: Flag
webhook -> api++: PUT /books/{id}?outdated=true
api --> webhook: 204 Accepted
note right: Enqueue
webhook --> edTechBooks--: ACK
note left: Dequeue
deactivate edTechBooks
==Fetch updated book==
api -> contentUpdater++: Update Book
note right: Flag
contentUpdater --> api: 204 Accepted
note left: Enqueue
note right: Dequeue
deactivate api
loop #DDDDDD for each book
    ==Fetch book, update database==
    contentUpdater -> edTechBooks++: GET Book
    note right: Flag
    edTechBooks --> contentUpdater--: Book
    contentUpdater -> api++: PUT /books/{id}?content={content}
    api -> database++: Update Book
    database --> api--: Success
    api --> contentUpdater: 200 OK
    note left: Dequeue
    note right: Enqueue
    deactivate contentUpdater
    loop #CCCCCC for each mobile app instance that has this book downloaded
        ==Queue notification for mobile app==
        api -> mpnServer++: Book Updated
        note right: Flag
        mpnServer --> api: ACK
        note left: Enqueue
        note right: Dequeue
        deactivate api
        ==Push notification to mobile app==
        mpnServer -> mobileApp++: Book Updated
        note left: Flag
        mobileApp --> mpnServer: ACK
        note right: Enqueue
        note left: Dequeue
        deactivate mpnServer
        ==Download new book==
        mobileApp -> api++: GET /book/{id}
        note left: Flag
        api -> database++: Query Book
        database --> api--: Book
        api --> mobileApp--: Book
        note left: Dequeue
        deactivate mobileApp
    end
end
@enduml